### ISSUE TITLE
`tryptools.cell_morphology_analysis` can try to read out-of-bounds image data.

### ISSUE THREAD

**Issue by zephyris** [zephyris/tryptag#8]
To replicate:
```
from tryptag import TrypTag, tryptools
tryptag = TrypTag()
cell_image = tryptag.open_cell("Tb927.10.10630", "c", 2, 60)
morph = tryptools.cell_morphology_analysis(cell_image.phase_mask, cell_image.dna_mask, cell_image.dna)
```
Gives:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/richard/.local/lib/python3.8/site-packages/tryptag/tryptools/tryptools.py", line 165, in cell_morphology_analysis
    midline_analysis = cell_midline_analysis(pth)
  File "/home/richard/.local/lib/python3.8/site-packages/tryptag/tryptools/tryptools.py", line 121, in cell_midline_analysis
    pth_skeleton = _mask_pruned_skeleton(pth, prefilter_radius, min_length_pruning) # MAGIC NUMBERS: Radius for prefiltering, length for pruning branches
  File "/home/richard/.local/lib/python3.8/site-packages/tryptag/tryptools/tryptools.py", line 49, in _mask_pruned_skeleton
    if (a != 0 or b != 0) and skeleton[cy + b, cx + a] == 1:
```

**Comment by zephyris** [comment]
Resolved - one bug and one un-useful behaviour in loading cells. 1) Set non-255 pixels to 0 during mask loading, 2a) ensure a black border on any `phase_mask` images and 2b) add a padded crop option to ensure no clipping of cell phase mask.
